#!/bin/bash

mkdir -p ./package

skeleton1="package util

/**
 * Generated by zipper.sh on `date --iso-8601`.
 */
object WeightsConfigContainer {
  val weights: Seq[String] = Seq("

skeleton2=")
}"
acc=$skeleton1
first=true
for file in $1/*
do
    #echo "$file"
    temp=$(<"$file")
    if $first
    then
        acc="$acc \"\"\"$temp\"\"\""
        first=false
        echo "first"
    else
        acc="$acc , \"\"\"$temp\"\"\""
    fi
done

acc="$acc $skeleton2"

mkdir -p package/util
echo "$acc" > package/util/asdf.scala

curr=`pwd`
cd ./src/main/scala
while read path
do
    cp --parents $path $curr/package
done < $curr/zip_include.txt

cd $curr

cp -r ./include-libs/* ./package/

zip -r ~/testbot.zip ./package/